spring:
  datasource:
    url: jdbc:postgresql://ep-wild-cherry-add06zd9-pooler.c-2.us-east-1.aws.neon.tech/neondb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate  # don’t modify schema automatically in prod

  sql:
    init:
      mode: never

server:
  port: 8080
